apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-app
spec:
  selector:
    matchLabels:
      app: yolo-app
  template:
    metadata:
      labels:
        app: yolo-app
    spec:
      containers:
      - name: yolo-client
        image: condabu/yolo-frontend:1.0.0
        ports:
        - containerPort: 3000
      - name: yolo-backend
        image: condabu/yolo-backend:1.0.0
        ports:
        - containerPort: 5000
      - name: yolo-database
        image: mongo:latest
        ports:
        - containerPort: 27017
