apiVersion: v1
kind: Service
metadata:
  name: yolo-client-service
spec:
  type: LoadBalancer
  selector:
    app: yolo-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: yolo-backend-service
spec:
  type: ClusterIP
  selector:
    app: yolo-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: yolo-database-service
spec:
  type: ClusterIP
  selector:
    app: yolo-app
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
