---
# tasks file for start_services

- name: Create mongo_data volume
  docker_volume:
    name: "{{mongo_data}}"

- name: Create network
  docker_network:
    name: "{{ network }}"
    driver: bridge

- name: Start yolo-database container
  docker_container:
    name: yolo-database
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - 'mongo_data:/data/db'
    networks:
      - name: "{{ network }}"
    state: started

- name: Start yolo-backend container
  docker_container:
    name: yolo-backend
    image: condabu/yolo-backend:1.0.0
    ports:
      - '5000:5000'
    networks:
      - name: "{{ network }}"
    env:
      MONGODB_URI: mongodb://yolo-database/
    state: started

- name: Start yolo-client container
  docker_container:
    name: yolo-client
    image: condabu/yolo-client:1.0.0
    ports:
      - '3000:3000'
    networks:
      - name: "{{ network }}"
    state: started
