---
- name: Provision Server
  hosts: all
  connection: ssh
  become: yes

  #variables
  vars:
    clone_from: "https://github.com/charlesmagutu/yolo.git"
    clone_to: "/app"
    
    yolo_frontend_image: "yolo-client"
    yolo_frontend_dockerfile: "/app/client/Dockerfile"
    yolo_frontend_build_context: "/app/client/"

    yolo_backend_image: "yolo-backend"
    yolo_backend_dockerfile: "/app/backend/Dockerfile" 
    yolo_backend_build_context: /app/backend/
   
  roles:
    #installs docker and its dependecnies on target hosts
    - docker 
    #clones the code from repo to target host
    - clone_app 
    # pull mongo db image from docker hub
    - database
    # build backend docker container and configures it from source code
    - backend
    # build frontend docker container and configures it from source code
    - frontend
    # starts the docker services frontend, backend, and databse
    - start_services