---
- name: Provision Server
  hosts: prod 
  become: yes

  roles:
    - ../ansible/docker

- name: Clone Project from Git
  hosts: prod 
  become: yes

  vars:
    clone_from: "https://github.com/charlesmagutu/yolo.git"
    clone_to: "app"
  roles:
    - clone_app 
