---
- name: Provision Server
  hosts: prod 
  become: yes

  vars:
    clone_from: "https://github.com/charlesmagutu/yolo.git"
    clone_to: "app"
    
    yolo_frontend_image: "yolo-client"
    yolo_frontend_dockerfile: "app/client/Dockerfile"

    yolo_backend_image: "yolo-backend"
    yolo_backend_dockerfile: "app/backend/Dockerfile" 

  roles:
    - docker 
    - clone_app 
    - frontend
    - backend
    - database
