---
- name: Provision Server
  hosts: prod
  connection: ssh
  become: yes

  vars:
    clone_from: "https://github.com/charlesmagutu/yolo.git"
    clone_to: "/app"
    # mongo_volume: "mongo_data"
    
    yolo_frontend_image: "yolo-client"
    yolo_frontend_dockerfile: "/app/client/Dockerfile"
    yolo_frontend_build_context: "/app/client/"

    yolo_backend_image: "yolo-backend"
    yolo_backend_dockerfile: "/app/backend/Dockerfile" 
    yolo_backend_build_context: /app/backend/

  roles:
    - docker 
    - clone_app 
    - backend
    # - frontend
    - database
    - start_services
